### ISSUE TITLE
DevCamp Website Broken Course Link

### ISSUE THREAD

**Issue by curtismckee** [jordanhudgens/devcamp-bug-tracker#3]
If you navigate to [DevCamp Courses](https://devcamp.com/courses) and scroll down to the screenshot. The link is broken.

![screen shot 2016-11-24 at 11 36 54 pm](https://cloud.githubusercontent.com/assets/7895798/20616378/19e6d2ac-b29f-11e6-9832-bf9530d01de6.png)

The link redirects to [this link](https://devcamp.com/courses/introduction-to-rails) and gives this error:
![screen shot 2016-11-24 at 11 42 06 pm](https://cloud.githubusercontent.com/assets/7895798/20616456/acbc57a0-b29f-11e6-9b4e-0102667f0468.png)

**Comment by jordanhudgens** [comment]
Thanks! Fix is being pushed up now. These will all eventually point to promotional pages but I haven't finished writing the copy yet, should be done by next week. Changing it to a # ref for now.
